### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Kriesse** [mafintosh/dat-drop#1]
### Empty State (user just opened the app)

![dat-drop-empty](https://cloud.githubusercontent.com/assets/53684/17525370/b482d6e4-5e62-11e6-9e5e-f36fdaa64d21.png)
### Sharing

![dat-drop-peers](https://cloud.githubusercontent.com/assets/53684/17525288/66ec3e98-5e62-11e6-9b04-cdabf18803d4.png)

**Comment by Kriesse** [comment]
@mafintosh some first ideas for the empty screen, and where to place buttons and meta info once the dat is created.
do the items in the bottom bar make sense?
what else is needed?

**Comment by mafintosh** [comment]
@Kriesse i like this a lot! I think this is enough for a forst version

**Comment by juliangruber** [comment]
i really like this too!

**Comment by Kriesse** [comment]
Closing; let's open separate issues for UI details.
